import 'package:flutter/foundation.dart';

/// Lightweight runtime i18n. Strings live in this file (no .arb codegen) and
/// the active locale is a [ValueNotifier] watched by the root MaterialApp, so
/// changing the locale rebuilds the whole tree and every `AppStrings.t(...)`
/// call returns the new translation immediately.
///
/// Falls back to English then French for missing keys, so partial translations
/// degrade gracefully instead of throwing.
abstract final class AppStrings {
  /// BCP-47 primary subtag of the active UI language. Defaults to `en`.
  static final ValueNotifier<String> currentBcp47 = ValueNotifier<String>('en');

  static void setFromCode(String bcp47) {
    final code = _normalize(bcp47);
    if (code.isEmpty) return;
    if (!_maps.containsKey(code)) return;
    if (code == currentBcp47.value) return;
    currentBcp47.value = code;
  }

  /// Translate by key. Supports simple `{var}` placeholder substitution.
  static String t(String key, {Map<String, String>? args}) {
    final code = currentBcp47.value;
    final raw = _maps[code]?[key] ?? _maps['en']?[key] ?? _maps['fr']?[key] ?? key;
    if (args == null || args.isEmpty) return raw;
    var out = raw;
    args.forEach((k, v) => out = out.replaceAll('{$k}', v));
    return out;
  }

  static String _normalize(String code) {
    final t = code.trim().toLowerCase();
    if (t.isEmpty) return '';
    return t.split('-').first;
  }

  static final Map<String, Map<String, String>> _maps = {
    'fr': _fr,
    'en': _en,
    'es': _es,
    'de': _de,
    'it': _it,
    'pt': _pt,
    'nl': _nl,
    'ar': _ar,
    'ru': _ru,
    'zh': _zh,
    'ja': _ja,
    'ko': _ko,
  };

  // ─── French ───────────────────────────────────────────────────────────────
  static const Map<String, String> _fr = {
    'nav_search': 'Recherche',
    'nav_call': 'Appel',
    'nav_chat': 'Chat',
    'nav_tab3': 'Profil',
    'tab_placeholder_soon': 'Bientôt',
    'profile_title': 'Profil',
    'profile_followers': 'Abonnés',
    'profile_following': 'Abonnements',
    'profile_bio_placeholder': 'Présente-toi en 2 mots ✏️',
    // Settings page
    'settings_title': 'Paramètres',
    'settings_section_account': 'Compte',
    'settings_section_notifications': 'Notifications',
    'settings_section_privacy': 'Confidentialité',
    'settings_section_lang': 'Langue & traduction',
    'settings_section_subscription': 'Abonnement',
    'settings_section_help': 'Aide & légal',
    'settings_email': 'Email',
    'settings_change_password': 'Changer le mot de passe',
    'settings_delete_account': 'Supprimer le compte',
    'settings_push': 'Notifications push',
    'settings_sounds': 'Sons des notifications',
    'settings_in_app_sounds': "Sons dans l'app",
    'settings_blocked': 'Liste des bloqués',
    'settings_hide_online': 'Cacher mon statut en ligne',
    'settings_lang_interface': "Langue de l'interface",
    'settings_auto_translate': 'Auto-traduction par défaut',
    'settings_audio_output': 'Sortie audio',
    'settings_audio_speaker': 'Haut-parleur',
    'settings_audio_earpiece': 'Écouteur',
    'settings_manage_sub': 'Gérer mon abonnement',
    'settings_restore_purchase': 'Restaurer un achat',
    'settings_help_faq': "Centre d'aide / FAQ",
    'settings_contact': 'Contacter le support',
    'settings_terms': "Conditions d'utilisation",
    'settings_privacy': 'Politique de confidentialité',
    'settings_version': 'Version',
    'settings_change_pwd_body':
        'Un email avec un lien de réinitialisation va être envoyé à {email}. Tu pourras choisir un nouveau mot de passe en cliquant sur le lien.',
    'settings_change_pwd_confirm': 'Envoyer le lien',
    'settings_delete_title': 'Supprimer le compte ?',
    'settings_delete_body':
        'Ton profil, tes amis et tes demandes seront effacés. Tu seras déconnecté immédiatement. Cette action est irréversible.',
    'settings_delete_confirm': 'Supprimer',
    'settings_save_failed': "Impossible d'enregistrer ce paramètre.",
    'settings_email_not_found': 'Adresse email introuvable.',
    'settings_email_sent': 'Email envoyé. Vérifie ta boîte.',
    'settings_subscription_appstore':
        "La gestion d'abonnement se fait depuis ton App Store / Play Store.",
    'settings_restore_soon': 'Restauration des achats — bientôt disponible.',
    'settings_help_soon': "Centre d'aide — bientôt disponible.",
    'settings_contact_soon':
        'Écris-nous à support@swayco.app (à venir : ouverture mailto).',
    'settings_terms_soon': "Conditions d'utilisation — bientôt en ligne.",
    'settings_privacy_soon':
        'Politique de confidentialité — bientôt en ligne.',
    // Blocked-users sub-screen
    'blocked_title': 'Bloqués',
    'blocked_unblock_title_q': 'Débloquer {name} ?',
    'blocked_unblock_body':
        'Cette personne pourra à nouveau te trouver, te contacter et voir tes messages.',
    'blocked_unblock_confirm': 'Débloquer',
    'blocked_empty_title': 'Aucun utilisateur bloqué',
    'blocked_empty_body':
        "Bloque un profil depuis le menu d'une discussion.",
    'error_prefix': 'Erreur : {msg}',
    // Generic actions
    'block': 'Bloquer',
    'unblock': 'Débloquer',
    'delete': 'Supprimer',
    'save': 'Enregistrer',
    'report': 'Signaler',
    'report_q': 'Signaler {name} ?',
    'report_body':
        'Choisis une raison. Notre équipe examine chaque signalement.',
    'report_details_hint': 'Plus de détails (facultatif)',
    'report_submit': 'Envoyer le signalement',
    'report_thanks': 'Signalement envoyé. Merci.',
    'report_failed': 'Signalement échoué. Réessaye plus tard.',
    'report_reason_spam': 'Spam',
    'report_reason_harassment': 'Harcèlement / abus',
    'report_reason_fake': 'Faux profil',
    'report_reason_inappropriate': 'Contenu inapproprié',
    'report_reason_underage': 'Mineur',
    'report_reason_scam': 'Arnaque',
    'report_reason_other': 'Autre',
    'restart': 'Recommencer',
    // Discover
    'discover_title': 'Discover',
    'search_chercher': 'Chercher',
    'search_friend_hint': "Prénom de l'ami",
    'filters': 'Filtres',
    'search_intro_hint': "Tape les premières lettres d'un prénom.",
    'discover_done': "C'est tout pour aujourd'hui",
    'send_emoji': 'Envoyer 👋',
    'add_friend_short': 'Ajouter',
    'like_save_failed': "Impossible d'enregistrer le like.",
    'friendship_friend': 'Ami',
    'friendship_sent': 'Envoyé',
    'friendship_pending_in': 'À accepter',
    // Chat list
    'messages_title': 'Messages',
    'chat_no_friends_title': "Pas encore d'amis",
    'chat_no_friends_body':
        "Va dans l'onglet Recherche pour trouver quelqu'un par son prénom, puis envoie une demande d'ami pour pouvoir discuter avec lui.",
    'chat_no_name': 'Sans nom',
    'chat_tap_to_chat': 'Toucher pour discuter',
    'tooltip_more': 'Plus',
    'view_profile': 'Voir profil',
    // Chat thread
    'block_peer_q': 'Bloquer {name} ?',
    'unblock_peer_q': 'Débloquer {name} ?',
    'block_peer_body':
        "Cette personne ne pourra plus te trouver, te contacter ni t'appeler. Tu peux annuler depuis Paramètres → Bloqués.",
    'unblock_peer_body':
        'Cette personne pourra à nouveau te trouver, te contacter et voir tes messages.',
    'no_messages': 'Aucun message — écris le premier !',
    'tooltip_call': 'Appeler',
    'composer_message_hint': 'Message',
    // Profile
    'profile_default_title': 'Profil',
    'delete_photo_q': 'Supprimer la photo ?',
    'delete_photo_body':
        'Ta photo Discover sera retirée. Tu pourras en uploader une nouvelle à tout moment.',
    'bio_editor_title': 'Ta présentation',
    // Incoming call modal
    'incoming_someone': "Quelqu'un",
    'cant_join_call': "Impossible de rejoindre l'appel : {msg}",
    'incoming_call_label': 'Appel entrant…',
    'decline': 'Refuser',
    'accept': 'Accepter',
    // Likes received
    'who_liked_me': "Qui m'a liké",
    'no_one_liked_yet': "Personne ne t'a encore liké",
    'like_explainer':
        "Quand quelqu'un appuie sur le ❤ de ta carte Discover, tu le verras apparaître ici.",
    'profile_speaks': 'Parle {lang}',
    'profile_no_language': 'Aucune langue',
    'profile_call_language_warning':
        "Lors de tes appels tu devras parler uniquement {lang} pour que la traduction fonctionne.",
    'profile_edit': 'Modifier',
    'profile_message': 'Message',
    'profile_loading': 'Chargement...',
    'profile_anonymous': 'Sans nom',
    'profile_email_private': 'Privé · visible uniquement par toi',
    'profile_signout': 'Se déconnecter',
    'profile_signout_confirm_title': 'Se déconnecter ?',
    'profile_signout_confirm_body':
        'Tu pourras te reconnecter avec ton e-mail et ton mot de passe.',
    'cancel': 'Annuler',

    'credits_free_title': 'Compte gratuit · 2h offertes / semaine',
    'credits_pro_title': 'Compte Premium',
    'credits_remaining': 'Crédits restants',
    'credits_used_total': 'Temps total d\'appel',
    'credits_upgrade_cta': 'Passer Premium',
    'premium_title': 'Premium',
    'premium_offer_label': 'Premium hebdomadaire',
    'premium_bullet_minutes':
        '3 à 5 heures d\'appel traduit par semaine',
    'premium_bullet_unlimited_calls':
        'Appels illimités même sans traduction active',
    'premium_bullet_priority':
        'Qualité de traduction prioritaire et latence réduite',
    'premium_continue': 'Continuer',
    'premium_activated': '💎 Premium activé pour une semaine.',
    'credits_exhausted_banner':
        'Crédits épuisés — la traduction est désactivée, l\'appel continue.',

    'login_title_signin': 'Bon retour',
    'login_title_signup': 'Créer un compte',
    'login_subtitle_signin': 'Connecte-toi à ton compte.',
    'login_subtitle_signup': 'Un e-mail, un mot de passe, c\'est tout.',
    'login_email_label': 'E-mail',
    'login_email_hint': 'toi@exemple.com',
    'login_password_label': 'Mot de passe',
    'login_forgot': 'Mot de passe oublié ?',
    'login_btn_signin': 'Se connecter',
    'login_btn_signup': 'S\'inscrire',
    'login_no_account': 'Pas encore de compte ?',
    'login_have_account': 'Déjà un compte ?',
    'login_err_email': 'Entre une adresse e-mail valide.',
    'login_err_password': 'Le mot de passe doit faire 6 caractères ou plus.',
    'login_check_inbox':
        'Vérifie ta boîte mail : on t\'a envoyé un lien de confirmation.',
    'login_resend_confirm': 'Renvoyer le mail de confirmation',
    'login_resend_sent':
        'Mail de confirmation renvoyé. Vérifie ta boîte (et les spams).',
    'login_err_not_confirmed':
        'E-mail pas encore confirmé. Clique sur le lien reçu par mail, ou renvoie-le.',
    'login_reset_sent':
        'Si un compte existe pour cet e-mail, un lien de réinitialisation a été envoyé.',

    'onb_welcome_title': 'Bienvenue',
    'onb_welcome_subtitle': "Dis-nous comment t'appeler dans les appels.",
    'onb_language_title': 'Ta langue',
    'onb_language_subtitle':
        "Choisis la langue que tu parles. La langue de l'autre est détectée automatiquement quand il rejoint l'appel.",
    'onb_first_name_label': 'Prénom',
    'onb_first_name_hint': 'ex. Alex',
    'onb_next': 'Suivant',
    'onb_back': 'Retour',
    'onb_finish': 'Commencer',
    'onb_save': 'Enregistrer',
    'onb_need_name': 'Entre ton prénom.',
    'onb_need_language': 'Choisis la langue que tu parles.',
    'onb_language_picker_label': 'La langue que tu parles',
    'onb_profile_title': 'Ton profil',
    'onb_translation_help':
        "En appel, on traduira automatiquement la voix de l'autre dans ta langue, et la tienne dans la sienne.",

    'join_title': 'Rejoindre une room',
    'join_desc':
        'Choisis un nom de room et partage-le avec une autre personne. Vous devez utiliser le même nom pour vous retrouver en 1-on-1.',
    'join_room_label': 'Nom de la room',
    'join_room_hint': 'ex. diner-avec-sam',
    'join_name_label': 'Ton prénom',
    'join_name_hint': 'Comme les autres te verront',
    'join_speak': 'Tu parles {lang}',
    'join_no_lang': 'Aucune langue choisie',
    'join_lang_subtitle': "La langue de l'autre est détectée automatiquement.",
    'join_edit_profile': 'Modifier ton profil',
    'join_error_room': 'Entre un nom de room (3+ caractères) et ton prénom.',
    'join_error_room_format':
        "Le nom de room doit faire 3 à 64 caractères : lettres, chiffres, _ et - uniquement (pas d'espace ni #). Exemple : diner-avec-sam",
    'join_error_lang': 'Choisis ta langue dans ton profil avant de rejoindre.',
    'join_button': "Démarrer l'appel",
    'join_header_title': 'Calls',
    'join_header_subtitle': 'LiveKit · 1-on-1',
    'join_header_token_server': 'Token server: {api}',
    'join_header_profile_tooltip': 'Ton profil',
  };

  // ─── English ──────────────────────────────────────────────────────────────
  static const Map<String, String> _en = {
    'nav_search': 'Search',
    'nav_call': 'Call',
    'nav_chat': 'Chat',
    'nav_tab3': 'Profile',
    'tab_placeholder_soon': 'Soon',
    'profile_title': 'Profile',
    'profile_followers': 'Followers',
    'profile_following': 'Following',
    'profile_bio_placeholder': 'Tell us about yourself in 2 words ✏️',
    'settings_title': 'Settings',
    'settings_section_account': 'Account',
    'settings_section_notifications': 'Notifications',
    'settings_section_privacy': 'Privacy',
    'settings_section_lang': 'Language & translation',
    'settings_section_subscription': 'Subscription',
    'settings_section_help': 'Help & legal',
    'settings_email': 'Email',
    'settings_change_password': 'Change password',
    'settings_delete_account': 'Delete account',
    'settings_push': 'Push notifications',
    'settings_sounds': 'Notification sounds',
    'settings_in_app_sounds': 'In-app sounds',
    'settings_blocked': 'Blocked users',
    'settings_hide_online': 'Hide my online status',
    'settings_lang_interface': 'Interface language',
    'settings_auto_translate': 'Auto-translate by default',
    'settings_audio_output': 'Audio output',
    'settings_audio_speaker': 'Speaker',
    'settings_audio_earpiece': 'Earpiece',
    'settings_manage_sub': 'Manage subscription',
    'settings_restore_purchase': 'Restore a purchase',
    'settings_help_faq': 'Help center / FAQ',
    'settings_contact': 'Contact support',
    'settings_terms': 'Terms of use',
    'settings_privacy': 'Privacy policy',
    'settings_version': 'Version',
    'settings_change_pwd_body':
        'A reset-link email will be sent to {email}. You can choose a new password by clicking the link.',
    'settings_change_pwd_confirm': 'Send link',
    'settings_delete_title': 'Delete account?',
    'settings_delete_body':
        'Your profile, friends and requests will be erased. You will be signed out immediately. This action cannot be undone.',
    'settings_delete_confirm': 'Delete',
    'settings_save_failed': "Couldn't save this setting.",
    'settings_email_not_found': 'Email address not found.',
    'settings_email_sent': 'Email sent. Check your inbox.',
    'settings_subscription_appstore':
        'Manage your subscription from the App Store / Play Store.',
    'settings_restore_soon': 'Purchase restore — coming soon.',
    'settings_help_soon': 'Help center — coming soon.',
    'settings_contact_soon':
        'Write to us at support@swayco.app (mailto coming soon).',
    'settings_terms_soon': 'Terms of use — coming soon.',
    'settings_privacy_soon': 'Privacy policy — coming soon.',
    'blocked_title': 'Blocked',
    'blocked_unblock_title_q': 'Unblock {name}?',
    'blocked_unblock_body':
        'They will be able to find you, contact you and see your messages again.',
    'blocked_unblock_confirm': 'Unblock',
    'blocked_empty_title': 'No blocked users',
    'blocked_empty_body':
        'Block a profile from the menu of a conversation.',
    'error_prefix': 'Error: {msg}',
    'block': 'Block',
    'unblock': 'Unblock',
    'delete': 'Delete',
    'save': 'Save',
    'restart': 'Restart',
    'report': 'Report',
    'report_q': 'Report {name}?',
    'report_body':
        'Pick a reason. Our team reviews every report.',
    'report_details_hint': 'More details (optional)',
    'report_submit': 'Submit report',
    'report_thanks': 'Report submitted. Thank you.',
    'report_failed': 'Report failed. Please try again later.',
    'report_reason_spam': 'Spam',
    'report_reason_harassment': 'Harassment / abuse',
    'report_reason_fake': 'Fake profile',
    'report_reason_inappropriate': 'Inappropriate content',
    'report_reason_underage': 'Underage user',
    'report_reason_scam': 'Scam',
    'report_reason_other': 'Other',
    'discover_title': 'Discover',
    'search_chercher': 'Search',
    'search_friend_hint': "Friend's first name",
    'filters': 'Filters',
    'search_intro_hint': 'Type the first letters of a first name.',
    'discover_done': "That's all for today",
    'send_emoji': 'Send 👋',
    'add_friend_short': 'Add',
    'like_save_failed': "Couldn't save the like.",
    'friendship_friend': 'Friend',
    'friendship_sent': 'Sent',
    'friendship_pending_in': 'To accept',
    'messages_title': 'Messages',
    'chat_no_friends_title': 'No friends yet',
    'chat_no_friends_body':
        'Go to the Search tab to find someone by their first name, then send a friend request to chat with them.',
    'chat_no_name': 'No name',
    'chat_tap_to_chat': 'Tap to chat',
    'tooltip_more': 'More',
    'view_profile': 'View profile',
    'block_peer_q': 'Block {name}?',
    'unblock_peer_q': 'Unblock {name}?',
    'block_peer_body':
        'They will no longer be able to find you, contact you or call you. You can undo this from Settings → Blocked.',
    'unblock_peer_body':
        'They will be able to find you, contact you and see your messages again.',
    'no_messages': 'No messages — write the first one!',
    'tooltip_call': 'Call',
    'composer_message_hint': 'Message',
    'profile_default_title': 'Profile',
    'delete_photo_q': 'Delete photo?',
    'delete_photo_body':
        'Your Discover photo will be removed. You can upload a new one at any time.',
    'bio_editor_title': 'Your bio',
    'incoming_someone': 'Someone',
    'cant_join_call': "Can't join the call: {msg}",
    'incoming_call_label': 'Incoming call…',
    'decline': 'Decline',
    'accept': 'Accept',
    'who_liked_me': 'Who liked me',
    'no_one_liked_yet': 'No one has liked you yet',
    'like_explainer':
        "When someone taps the ❤ on your Discover card, you'll see them here.",
    'profile_speaks': 'Speaks {lang}',
    'profile_no_language': 'No language',
    'profile_call_language_warning':
        'During calls you have to speak only {lang} so the translation works.',
    'profile_edit': 'Edit',
    'profile_message': 'Message',
    'profile_loading': 'Loading...',
    'profile_anonymous': 'No name',
    'profile_email_private': 'Private · only visible to you',
    'profile_signout': 'Sign out',
    'profile_signout_confirm_title': 'Sign out?',
    'profile_signout_confirm_body':
        'You can sign back in with your email and password.',
    'cancel': 'Cancel',

    'credits_free_title': 'Free plan · 2h/week included',
    'credits_pro_title': 'Premium account',
    'credits_remaining': 'Credits left',
    'credits_used_total': 'Total call time',
    'credits_upgrade_cta': 'Go Premium',
    'premium_title': 'Premium',
    'premium_offer_label': 'Premium Weekly',
    'premium_bullet_minutes': '3 to 5 hours of translated calls per week',
    'premium_bullet_unlimited_calls':
        'Unlimited calls even without active translation',
    'premium_bullet_priority':
        'Priority translation quality and lower latency',
    'premium_continue': 'Continue',
    'premium_activated': '💎 Premium activated for one week.',
    'credits_exhausted_banner':
        'Out of credits — translation is off, the call continues.',

    'login_title_signin': 'Welcome back',
    'login_title_signup': 'Create an account',
    'login_subtitle_signin': 'Sign in to your account.',
    'login_subtitle_signup': 'Just an email and a password.',
    'login_email_label': 'Email',
    'login_email_hint': 'you@example.com',
    'login_password_label': 'Password',
    'login_forgot': 'Forgot password?',
    'login_btn_signin': 'Sign in',
    'login_btn_signup': 'Sign up',
    'login_no_account': 'No account yet?',
    'login_have_account': 'Already have an account?',
    'login_err_email': 'Enter a valid email address.',
    'login_err_password': 'Password must be at least 6 characters.',
    'login_check_inbox': 'Check your inbox — we sent you a confirmation link.',
    'login_resend_confirm': 'Resend confirmation email',
    'login_resend_sent':
        'Confirmation email resent. Check your inbox (and spam folder).',
    'login_err_not_confirmed':
        'Email not confirmed yet. Click the link we sent you, or resend it.',
    'login_reset_sent':
        'If an account exists for that email, a reset link has been sent.',

    'onb_welcome_title': 'Welcome',
    'onb_welcome_subtitle': 'Tell us how to call you in calls.',
    'onb_language_title': 'Your language',
    'onb_language_subtitle':
        "Pick the language you speak. The other person's language is detected automatically when they join the call.",
    'onb_first_name_label': 'First name',
    'onb_first_name_hint': 'e.g. Alex',
    'onb_next': 'Next',
    'onb_back': 'Back',
    'onb_finish': 'Get started',
    'onb_save': 'Save',
    'onb_need_name': 'Enter your first name.',
    'onb_need_language': 'Pick the language you speak.',
    'onb_language_picker_label': 'The language you speak',
    'onb_profile_title': 'Your profile',
    'onb_translation_help':
        "In a call, we'll automatically translate the other person's voice into your language and yours into theirs.",

    'join_title': 'Join a room',
    'join_desc':
        'Pick any room name and share it with one other person. Both of you must use the same name to connect 1-on-1.',
    'join_room_label': 'Room name',
    'join_room_hint': 'e.g. dinner-with-sam',
    'join_name_label': 'Your first name',
    'join_name_hint': 'As others will see you',
    'join_speak': 'You speak {lang}',
    'join_no_lang': 'No language selected',
    'join_lang_subtitle': "The other person's language is detected automatically.",
    'join_edit_profile': 'Edit your profile',
    'join_error_room': 'Enter a room name (3+ characters) and your first name.',
    'join_error_room_format':
        'Room name must be 3-64 characters: letters, numbers, _ and - only (no spaces or #). Example: dinner-with-sam',
    'join_error_lang': 'Choose your language in your profile before joining.',
    'join_button': 'Start the call',
    'join_header_title': 'Calls',
    'join_header_subtitle': 'LiveKit · 1-on-1',
    'join_header_token_server': 'Token server: {api}',
    'join_header_profile_tooltip': 'Your profile',
  };

  // ─── Spanish ──────────────────────────────────────────────────────────────
  static const Map<String, String> _es = {
    'nav_search': 'Buscar',
    'nav_call': 'Llamada',
    'nav_chat': 'Chat',
    'nav_tab3': 'Perfil',
    'tab_placeholder_soon': 'Pronto',
    'profile_title': 'Perfil',
    'profile_followers': 'Seguidores',
    'profile_following': 'Siguiendo',
    'profile_bio_placeholder': 'Preséntate en 2 palabras ✏️',
    'settings_title': 'Ajustes',
    'settings_section_account': 'Cuenta',
    'settings_section_notifications': 'Notificaciones',
    'settings_section_privacy': 'Privacidad',
    'settings_section_lang': 'Idioma y traducción',
    'settings_section_subscription': 'Suscripción',
    'settings_section_help': 'Ayuda y legal',
    'settings_email': 'Correo',
    'settings_change_password': 'Cambiar contraseña',
    'settings_delete_account': 'Eliminar la cuenta',
    'settings_push': 'Notificaciones push',
    'settings_sounds': 'Sonidos de notificación',
    'settings_in_app_sounds': 'Sonidos en la app',
    'settings_blocked': 'Lista de bloqueados',
    'settings_hide_online': 'Ocultar mi estado en línea',
    'settings_lang_interface': 'Idioma de la interfaz',
    'settings_auto_translate': 'Auto-traducción por defecto',
    'settings_audio_output': 'Salida de audio',
    'settings_audio_speaker': 'Altavoz',
    'settings_audio_earpiece': 'Auricular',
    'settings_manage_sub': 'Gestionar suscripción',
    'settings_restore_purchase': 'Restaurar una compra',
    'settings_help_faq': 'Centro de ayuda / FAQ',
    'settings_contact': 'Contactar soporte',
    'settings_terms': 'Condiciones de uso',
    'settings_privacy': 'Política de privacidad',
    'settings_version': 'Versión',
    'settings_change_pwd_body':
        'Se enviará un correo con un enlace de restablecimiento a {email}. Podrás elegir una nueva contraseña al hacer clic en el enlace.',
    'settings_change_pwd_confirm': 'Enviar enlace',
    'settings_delete_title': '¿Eliminar la cuenta?',
    'settings_delete_body':
        'Tu perfil, amigos y solicitudes serán borrados. Se cerrará tu sesión inmediatamente. Esta acción es irreversible.',
    'settings_delete_confirm': 'Eliminar',
    'settings_save_failed': 'No se pudo guardar este ajuste.',
    'settings_email_not_found': 'Dirección de correo no encontrada.',
    'settings_email_sent': 'Correo enviado. Revisa tu bandeja.',
    'settings_subscription_appstore':
        'La gestión de la suscripción se hace desde tu App Store / Play Store.',
    'settings_restore_soon': 'Restauración de compras — próximamente.',
    'settings_help_soon': 'Centro de ayuda — próximamente.',
    'settings_contact_soon':
        'Escríbenos a support@swayco.app (mailto próximamente).',
    'settings_terms_soon': 'Condiciones de uso — próximamente.',
    'settings_privacy_soon': 'Política de privacidad — próximamente.',
    'blocked_title': 'Bloqueados',
    'blocked_unblock_title_q': '¿Desbloquear a {name}?',
    'blocked_unblock_body':
        'Esta persona podrá encontrarte, contactarte y ver tus mensajes de nuevo.',
    'blocked_unblock_confirm': 'Desbloquear',
    'blocked_empty_title': 'Ningún usuario bloqueado',
    'blocked_empty_body':
        'Bloquea un perfil desde el menú de una conversación.',
    'error_prefix': 'Error: {msg}',
    'block': 'Bloquear',
    'unblock': 'Desbloquear',
    'delete': 'Eliminar',
    'save': 'Guardar',
    'restart': 'Reiniciar',
    'discover_title': 'Discover',
    'search_chercher': 'Buscar',
    'search_friend_hint': 'Nombre del amigo',
    'filters': 'Filtros',
    'search_intro_hint': 'Escribe las primeras letras de un nombre.',
    'discover_done': 'Eso es todo por hoy',
    'send_emoji': 'Enviar 👋',
    'add_friend_short': 'Añadir',
    'like_save_failed': 'No se pudo guardar el like.',
    'friendship_friend': 'Amigo',
    'friendship_sent': 'Enviado',
    'friendship_pending_in': 'Por aceptar',
    'messages_title': 'Mensajes',
    'chat_no_friends_title': 'Sin amigos todavía',
    'chat_no_friends_body':
        'Ve a la pestaña de búsqueda para encontrar a alguien por su nombre, luego envía una solicitud de amistad para poder chatear.',
    'chat_no_name': 'Sin nombre',
    'chat_tap_to_chat': 'Toca para chatear',
    'tooltip_more': 'Más',
    'view_profile': 'Ver perfil',
    'block_peer_q': '¿Bloquear a {name}?',
    'unblock_peer_q': '¿Desbloquear a {name}?',
    'block_peer_body':
        'Esta persona ya no podrá encontrarte, contactarte ni llamarte. Puedes cancelar desde Ajustes → Bloqueados.',
    'unblock_peer_body':
        'Esta persona podrá encontrarte, contactarte y ver tus mensajes de nuevo.',
    'no_messages': 'Sin mensajes — ¡escribe el primero!',
    'tooltip_call': 'Llamar',
    'composer_message_hint': 'Mensaje',
    'profile_default_title': 'Perfil',
    'delete_photo_q': '¿Eliminar la foto?',
    'delete_photo_body':
        'Tu foto de Discover será eliminada. Podrás subir una nueva en cualquier momento.',
    'bio_editor_title': 'Tu presentación',
    'incoming_someone': 'Alguien',
    'cant_join_call': 'No se puede unirse a la llamada: {msg}',
    'incoming_call_label': 'Llamada entrante…',
    'decline': 'Rechazar',
    'accept': 'Aceptar',
    'who_liked_me': 'Quién me dio like',
    'no_one_liked_yet': 'Nadie te ha dado like todavía',
    'like_explainer':
        'Cuando alguien toque el ❤ de tu tarjeta Discover, lo verás aparecer aquí.',
    'profile_speaks': 'Habla {lang}',
    'profile_no_language': 'Sin idioma',
    'profile_call_language_warning':
        'Durante tus llamadas tendrás que hablar solo {lang} para que funcione la traducción.',
    'profile_edit': 'Editar',
    'profile_message': 'Mensaje',
    'profile_loading': 'Cargando...',
    'profile_anonymous': 'Sin nombre',

    'onb_welcome_title': 'Bienvenido',
    'onb_welcome_subtitle': 'Dinos cómo llamarte en las llamadas.',
    'onb_language_title': 'Tu idioma',
    'onb_language_subtitle':
        'Elige el idioma que hablas. El idioma de la otra persona se detecta automáticamente cuando se une a la llamada.',
    'onb_first_name_label': 'Nombre',
    'onb_first_name_hint': 'ej. Alex',
    'onb_next': 'Siguiente',
    'onb_back': 'Atrás',
    'onb_finish': 'Empezar',
    'onb_save': 'Guardar',
    'onb_need_name': 'Introduce tu nombre.',
    'onb_need_language': 'Elige el idioma que hablas.',
    'onb_language_picker_label': 'El idioma que hablas',
    'onb_profile_title': 'Tu perfil',
    'onb_translation_help':
        'En una llamada, traduciremos automáticamente la voz de la otra persona a tu idioma y la tuya al suyo.',

    'join_title': 'Unirse a una sala',
    'join_desc':
        'Elige un nombre de sala y compártelo con otra persona. Ambos deben usar el mismo nombre para conectarse 1-a-1.',
    'join_room_label': 'Nombre de la sala',
    'join_room_hint': 'ej. cena-con-sam',
    'join_name_label': 'Tu nombre',
    'join_name_hint': 'Como los demás te verán',
    'join_speak': 'Hablas {lang}',
    'join_no_lang': 'Ningún idioma elegido',
    'join_lang_subtitle': 'El idioma de la otra persona se detecta automáticamente.',
    'join_edit_profile': 'Editar tu perfil',
    'join_error_room': 'Introduce un nombre de sala (3+ caracteres) y tu nombre.',
    'join_error_room_format':
        'El nombre de la sala debe tener 3-64 caracteres: solo letras, números, _ y - (sin espacios ni #). Ejemplo: cena-con-sam',
    'join_error_lang': 'Elige tu idioma en tu perfil antes de unirte.',
    'join_button': 'Iniciar la llamada',
    'join_header_title': 'Llamadas',
    'join_header_subtitle': 'LiveKit · 1-a-1',
    'join_header_token_server': 'Servidor de tokens: {api}',
    'join_header_profile_tooltip': 'Tu perfil',
  };

  // ─── German ───────────────────────────────────────────────────────────────
  static const Map<String, String> _de = {
    'nav_search': 'Suche',
    'nav_call': 'Anruf',
    'nav_chat': 'Chat',
    'nav_tab3': 'Profil',
    'tab_placeholder_soon': 'Bald',
    'profile_title': 'Profil',
    'profile_followers': 'Follower',
    'profile_following': 'Folge ich',
    'block': 'Blockieren',
    'unblock': 'Entsperren',
    'delete': 'Löschen',
    'save': 'Speichern',
    'restart': 'Neu starten',
    'discover_title': 'Discover',
    'search_chercher': 'Suchen',
    'search_friend_hint': 'Vorname des Freundes',
    'filters': 'Filter',
    'search_intro_hint': 'Tippe die ersten Buchstaben eines Vornamens.',
    'discover_done': 'Das war alles für heute',
    'send_emoji': 'Senden 👋',
    'add_friend_short': 'Hinzufügen',
    'like_save_failed': 'Like konnte nicht gespeichert werden.',
    'friendship_friend': 'Freund',
    'friendship_sent': 'Gesendet',
    'friendship_pending_in': 'Zu akzeptieren',
    'messages_title': 'Nachrichten',
    'chat_no_friends_title': 'Noch keine Freunde',
    'chat_no_friends_body':
        'Gehe zum Suche-Tab, um jemanden mit Vornamen zu finden, und sende eine Freundschaftsanfrage, um zu chatten.',
    'chat_no_name': 'Kein Name',
    'chat_tap_to_chat': 'Tippe zum Chatten',
    'tooltip_more': 'Mehr',
    'view_profile': 'Profil ansehen',
    'block_peer_q': '{name} blockieren?',
    'unblock_peer_q': '{name} entsperren?',
    'block_peer_body':
        'Diese Person kann dich nicht mehr finden, kontaktieren oder anrufen. Du kannst dies in Einstellungen → Blockiert rückgängig machen.',
    'unblock_peer_body':
        'Diese Person kann dich wieder finden, kontaktieren und deine Nachrichten sehen.',
    'no_messages': 'Keine Nachrichten — schreibe die erste!',
    'tooltip_call': 'Anrufen',
    'composer_message_hint': 'Nachricht',
    'profile_default_title': 'Profil',
    'delete_photo_q': 'Foto löschen?',
    'delete_photo_body':
        'Dein Discover-Foto wird entfernt. Du kannst jederzeit ein neues hochladen.',
    'bio_editor_title': 'Deine Vorstellung',
    'incoming_someone': 'Jemand',
    'cant_join_call': 'Anruf kann nicht beigetreten werden: {msg}',
    'incoming_call_label': 'Eingehender Anruf…',
    'decline': 'Ablehnen',
    'accept': 'Annehmen',
    'who_liked_me': 'Wer mich gelikt hat',
    'no_one_liked_yet': 'Noch niemand hat dich gelikt',
    'like_explainer':
        'Wenn jemand auf das ❤ deiner Discover-Karte tippt, siehst du es hier.',
    'profile_speaks': 'Spricht {lang}',
    'profile_no_language': 'Keine Sprache',
    'profile_edit': 'Bearbeiten',
    'profile_message': 'Nachricht',
    'profile_loading': 'Lädt...',
    'profile_anonymous': 'Ohne Namen',

    'onb_welcome_title': 'Willkommen',
    'onb_welcome_subtitle': 'Sag uns, wie wir dich in Anrufen nennen sollen.',
    'onb_language_title': 'Deine Sprache',
    'onb_language_subtitle':
        'Wähle die Sprache, die du sprichst. Die Sprache der anderen Person wird automatisch erkannt, wenn sie dem Anruf beitritt.',
    'onb_first_name_label': 'Vorname',
    'onb_first_name_hint': 'z.B. Alex',
    'onb_next': 'Weiter',
    'onb_back': 'Zurück',
    'onb_finish': 'Loslegen',
    'onb_save': 'Speichern',
    'onb_need_name': 'Gib deinen Vornamen ein.',
    'onb_need_language': 'Wähle die Sprache, die du sprichst.',
    'onb_language_picker_label': 'Die Sprache, die du sprichst',
    'onb_profile_title': 'Dein Profil',
    'onb_translation_help':
        'In einem Anruf übersetzen wir automatisch die Stimme der anderen Person in deine Sprache und deine in ihre.',

    'join_title': 'Einem Raum beitreten',
    'join_desc':
        'Wähle einen Raumnamen und teile ihn mit einer anderen Person. Ihr müsst beide denselben Namen verwenden, um euch 1-zu-1 zu verbinden.',
    'join_room_label': 'Raumname',
    'join_room_hint': 'z.B. abendessen-mit-sam',
    'join_name_label': 'Dein Vorname',
    'join_name_hint': 'Wie andere dich sehen',
    'join_speak': 'Du sprichst {lang}',
    'join_no_lang': 'Keine Sprache gewählt',
    'join_lang_subtitle': 'Die Sprache der anderen Person wird automatisch erkannt.',
    'join_edit_profile': 'Profil bearbeiten',
    'join_error_room': 'Gib einen Raumnamen (mindestens 3 Zeichen) und deinen Vornamen ein.',
    'join_error_room_format':
        'Der Raumname muss 3-64 Zeichen lang sein: nur Buchstaben, Zahlen, _ und - (keine Leerzeichen oder #). Beispiel: abendessen-mit-sam',
    'join_error_lang': 'Wähle deine Sprache im Profil, bevor du beitrittst.',
    'join_button': 'Anruf starten',
    'join_header_title': 'Anrufe',
    'join_header_subtitle': 'LiveKit · 1-zu-1',
    'join_header_token_server': 'Token-Server: {api}',
    'join_header_profile_tooltip': 'Dein Profil',
  };

  // ─── Italian ──────────────────────────────────────────────────────────────
  static const Map<String, String> _it = {
    'nav_search': 'Cerca',
    'nav_call': 'Chiamata',
    'nav_chat': 'Chat',
    'nav_tab3': 'Profilo',
    'tab_placeholder_soon': 'Presto',
    'profile_title': 'Profilo',
    'profile_followers': 'Follower',
    'profile_following': 'Seguiti',
    'block': 'Blocca',
    'unblock': 'Sblocca',
    'delete': 'Elimina',
    'save': 'Salva',
    'restart': 'Ricomincia',
    'discover_title': 'Discover',
    'search_chercher': 'Cerca',
    'search_friend_hint': "Nome dell'amico",
    'filters': 'Filtri',
    'search_intro_hint': 'Digita le prime lettere di un nome.',
    'discover_done': 'Per oggi è tutto',
    'send_emoji': 'Invia 👋',
    'add_friend_short': 'Aggiungi',
    'like_save_failed': 'Impossibile salvare il mi piace.',
    'friendship_friend': 'Amico',
    'friendship_sent': 'Inviato',
    'friendship_pending_in': 'Da accettare',
    'messages_title': 'Messaggi',
    'chat_no_friends_title': 'Ancora nessun amico',
    'chat_no_friends_body':
        'Vai alla scheda Cerca per trovare qualcuno tramite nome, poi invia una richiesta di amicizia per chattare.',
    'chat_no_name': 'Senza nome',
    'chat_tap_to_chat': 'Tocca per chattare',
    'tooltip_more': 'Altro',
    'view_profile': 'Vedi profilo',
    'block_peer_q': 'Bloccare {name}?',
    'unblock_peer_q': 'Sbloccare {name}?',
    'block_peer_body':
        'Questa persona non potrà più trovarti, contattarti o chiamarti. Puoi annullare da Impostazioni → Bloccati.',
    'unblock_peer_body':
        'Questa persona potrà di nuovo trovarti, contattarti e vedere i tuoi messaggi.',
    'no_messages': 'Nessun messaggio — scrivi il primo!',
    'tooltip_call': 'Chiama',
    'composer_message_hint': 'Messaggio',
    'profile_default_title': 'Profilo',
    'delete_photo_q': 'Eliminare la foto?',
    'delete_photo_body':
        'La tua foto Discover sarà rimossa. Puoi caricarne una nuova in qualsiasi momento.',
    'bio_editor_title': 'La tua presentazione',
    'incoming_someone': 'Qualcuno',
    'cant_join_call': 'Impossibile unirsi alla chiamata: {msg}',
    'incoming_call_label': 'Chiamata in arrivo…',
    'decline': 'Rifiuta',
    'accept': 'Accetta',
    'who_liked_me': 'Chi mi ha messo mi piace',
    'no_one_liked_yet': 'Nessuno ti ha ancora messo mi piace',
    'like_explainer':
        'Quando qualcuno tocca il ❤ sulla tua scheda Discover, lo vedrai qui.',
    'profile_speaks': 'Parla {lang}',
    'profile_no_language': 'Nessuna lingua',
    'profile_edit': 'Modifica',
    'profile_message': 'Messaggio',
    'profile_loading': 'Caricamento...',
    'profile_anonymous': 'Senza nome',

    'onb_welcome_title': 'Benvenuto',
    'onb_welcome_subtitle': 'Dicci come chiamarti nelle chiamate.',
    'onb_language_title': 'La tua lingua',
    'onb_language_subtitle':
        "Scegli la lingua che parli. La lingua dell'altra persona viene rilevata automaticamente quando si unisce alla chiamata.",
    'onb_first_name_label': 'Nome',
    'onb_first_name_hint': 'es. Alex',
    'onb_next': 'Avanti',
    'onb_back': 'Indietro',
    'onb_finish': 'Inizia',
    'onb_save': 'Salva',
    'onb_need_name': 'Inserisci il tuo nome.',
    'onb_need_language': 'Scegli la lingua che parli.',
    'onb_language_picker_label': 'La lingua che parli',
    'onb_profile_title': 'Il tuo profilo',
    'onb_translation_help':
        "In una chiamata, tradurremo automaticamente la voce dell'altra persona nella tua lingua e la tua nella sua.",

    'join_title': 'Entra in una stanza',
    'join_desc':
        "Scegli un nome di stanza e condividilo con un'altra persona. Entrambi dovete usare lo stesso nome per collegarvi 1-a-1.",
    'join_room_label': 'Nome della stanza',
    'join_room_hint': 'es. cena-con-sam',
    'join_name_label': 'Il tuo nome',
    'join_name_hint': 'Come gli altri ti vedranno',
    'join_speak': 'Parli {lang}',
    'join_no_lang': 'Nessuna lingua scelta',
    'join_lang_subtitle': "La lingua dell'altra persona viene rilevata automaticamente.",
    'join_edit_profile': 'Modifica il tuo profilo',
    'join_error_room': 'Inserisci un nome di stanza (3+ caratteri) e il tuo nome.',
    'join_error_room_format':
        'Il nome della stanza deve avere 3-64 caratteri: solo lettere, numeri, _ e - (niente spazi né #). Esempio: cena-con-sam',
    'join_error_lang': 'Scegli la tua lingua nel profilo prima di entrare.',
    'join_button': 'Avvia la chiamata',
    'join_header_title': 'Chiamate',
    'join_header_subtitle': 'LiveKit · 1-a-1',
    'join_header_token_server': 'Token server: {api}',
    'join_header_profile_tooltip': 'Il tuo profilo',
  };

  // ─── Portuguese ───────────────────────────────────────────────────────────
  static const Map<String, String> _pt = {
    'nav_search': 'Pesquisa',
    'nav_call': 'Chamada',
    'nav_chat': 'Chat',
    'nav_tab3': 'Perfil',
    'tab_placeholder_soon': 'Em breve',
    'profile_title': 'Perfil',
    'profile_followers': 'Seguidores',
    'profile_following': 'A seguir',
    'block': 'Bloquear',
    'unblock': 'Desbloquear',
    'delete': 'Excluir',
    'save': 'Salvar',
    'restart': 'Recomeçar',
    'discover_title': 'Discover',
    'search_chercher': 'Pesquisar',
    'search_friend_hint': 'Nome do amigo',
    'filters': 'Filtros',
    'search_intro_hint': 'Digite as primeiras letras de um nome.',
    'discover_done': 'Por hoje é tudo',
    'send_emoji': 'Enviar 👋',
    'add_friend_short': 'Adicionar',
    'like_save_failed': 'Não foi possível salvar o curtir.',
    'friendship_friend': 'Amigo',
    'friendship_sent': 'Enviado',
    'friendship_pending_in': 'A aceitar',
    'messages_title': 'Mensagens',
    'chat_no_friends_title': 'Sem amigos ainda',
    'chat_no_friends_body':
        'Vá à aba Pesquisa para encontrar alguém pelo nome, depois envie um pedido de amizade para conversar.',
    'chat_no_name': 'Sem nome',
    'chat_tap_to_chat': 'Toque para conversar',
    'tooltip_more': 'Mais',
    'view_profile': 'Ver perfil',
    'block_peer_q': 'Bloquear {name}?',
    'unblock_peer_q': 'Desbloquear {name}?',
    'block_peer_body':
        'Esta pessoa não poderá mais encontrar você, contatá-lo ou ligar. Você pode desfazer em Configurações → Bloqueados.',
    'unblock_peer_body':
        'Esta pessoa poderá encontrá-lo, contatá-lo e ver suas mensagens novamente.',
    'no_messages': 'Sem mensagens — escreva a primeira!',
    'tooltip_call': 'Ligar',
    'composer_message_hint': 'Mensagem',
    'profile_default_title': 'Perfil',
    'delete_photo_q': 'Excluir a foto?',
    'delete_photo_body':
        'Sua foto Discover será removida. Você pode enviar uma nova a qualquer momento.',
    'bio_editor_title': 'Sua apresentação',
    'incoming_someone': 'Alguém',
    'cant_join_call': 'Impossível entrar na chamada: {msg}',
    'incoming_call_label': 'Chamada recebida…',
    'decline': 'Recusar',
    'accept': 'Aceitar',
    'who_liked_me': 'Quem me curtiu',
    'no_one_liked_yet': 'Ninguém te curtiu ainda',
    'like_explainer':
        'Quando alguém tocar no ❤ do seu cartão Discover, você verá aqui.',
    'profile_speaks': 'Fala {lang}',
    'profile_no_language': 'Sem língua',
    'profile_edit': 'Editar',
    'profile_message': 'Mensagem',
    'profile_loading': 'A carregar...',
    'profile_anonymous': 'Sem nome',

    'onb_welcome_title': 'Bem-vindo',
    'onb_welcome_subtitle': 'Diz-nos como te chamar nas chamadas.',
    'onb_language_title': 'A tua língua',
    'onb_language_subtitle':
        'Escolhe a língua que falas. A língua da outra pessoa é detetada automaticamente quando entra na chamada.',
    'onb_first_name_label': 'Primeiro nome',
    'onb_first_name_hint': 'ex. Alex',
    'onb_next': 'Seguinte',
    'onb_back': 'Voltar',
    'onb_finish': 'Começar',
    'onb_save': 'Guardar',
    'onb_need_name': 'Insere o teu primeiro nome.',
    'onb_need_language': 'Escolhe a língua que falas.',
    'onb_language_picker_label': 'A língua que falas',
    'onb_profile_title': 'O teu perfil',
    'onb_translation_help':
        'Numa chamada, traduziremos automaticamente a voz da outra pessoa para a tua língua e a tua para a dela.',

    'join_title': 'Entrar numa sala',
    'join_desc':
        'Escolhe um nome de sala e partilha-o com outra pessoa. Ambos têm de usar o mesmo nome para se ligarem 1-para-1.',
    'join_room_label': 'Nome da sala',
    'join_room_hint': 'ex. jantar-com-sam',
    'join_name_label': 'O teu primeiro nome',
    'join_name_hint': 'Como os outros te verão',
    'join_speak': 'Falas {lang}',
    'join_no_lang': 'Nenhuma língua escolhida',
    'join_lang_subtitle': 'A língua da outra pessoa é detetada automaticamente.',
    'join_edit_profile': 'Editar o teu perfil',
    'join_error_room': 'Insere um nome de sala (3+ caracteres) e o teu nome.',
    'join_error_room_format':
        'O nome da sala deve ter 3-64 caracteres: apenas letras, números, _ e - (sem espaços ou #). Exemplo: jantar-com-sam',
    'join_error_lang': 'Escolhe a tua língua no perfil antes de entrares.',
    'join_button': 'Iniciar a chamada',
    'join_header_title': 'Chamadas',
    'join_header_subtitle': 'LiveKit · 1-para-1',
    'join_header_token_server': 'Servidor de tokens: {api}',
    'join_header_profile_tooltip': 'O teu perfil',
  };

  // ─── Dutch ────────────────────────────────────────────────────────────────
  static const Map<String, String> _nl = {
    'nav_search': 'Zoeken',
    'nav_call': 'Oproep',
    'nav_chat': 'Chat',
    'nav_tab3': 'Profiel',
    'tab_placeholder_soon': 'Binnenkort',
    'profile_title': 'Profiel',
    'profile_followers': 'Volgers',
    'profile_following': 'Volgend',
    'block': 'Blokkeren',
    'unblock': 'Deblokkeren',
    'delete': 'Verwijderen',
    'save': 'Opslaan',
    'restart': 'Opnieuw beginnen',
    'discover_title': 'Discover',
    'search_chercher': 'Zoeken',
    'search_friend_hint': 'Voornaam van vriend',
    'filters': 'Filters',
    'search_intro_hint': 'Type de eerste letters van een voornaam.',
    'discover_done': 'Dat was het voor vandaag',
    'send_emoji': 'Verstuur 👋',
    'add_friend_short': 'Toevoegen',
    'like_save_failed': 'Kan like niet opslaan.',
    'friendship_friend': 'Vriend',
    'friendship_sent': 'Verzonden',
    'friendship_pending_in': 'Te accepteren',
    'messages_title': 'Berichten',
    'chat_no_friends_title': 'Nog geen vrienden',
    'chat_no_friends_body':
        'Ga naar het tabblad Zoeken om iemand op voornaam te vinden, en stuur een vriendschapsverzoek om te chatten.',
    'chat_no_name': 'Geen naam',
    'chat_tap_to_chat': 'Tik om te chatten',
    'tooltip_more': 'Meer',
    'view_profile': 'Profiel bekijken',
    'block_peer_q': '{name} blokkeren?',
    'unblock_peer_q': '{name} deblokkeren?',
    'block_peer_body':
        'Deze persoon kan jou niet meer vinden, contact opnemen of bellen. Je kunt dit ongedaan maken via Instellingen → Geblokkeerd.',
    'unblock_peer_body':
        'Deze persoon kan jou weer vinden, contact opnemen en je berichten zien.',
    'no_messages': 'Geen berichten — schrijf het eerste!',
    'tooltip_call': 'Bellen',
    'composer_message_hint': 'Bericht',
    'profile_default_title': 'Profiel',
    'delete_photo_q': 'Foto verwijderen?',
    'delete_photo_body':
        'Je Discover-foto wordt verwijderd. Je kunt op elk moment een nieuwe uploaden.',
    'bio_editor_title': 'Jouw bio',
    'incoming_someone': 'Iemand',
    'cant_join_call': 'Kan niet deelnemen aan de oproep: {msg}',
    'incoming_call_label': 'Inkomende oproep…',
    'decline': 'Weigeren',
    'accept': 'Accepteren',
    'who_liked_me': 'Wie heeft mij geliket',
    'no_one_liked_yet': 'Niemand heeft je nog geliket',
    'like_explainer':
        'Wanneer iemand op het ❤ van je Discover-kaart tikt, zie je het hier.',
    'profile_speaks': 'Spreekt {lang}',
    'profile_no_language': 'Geen taal',
    'profile_edit': 'Bewerken',
    'profile_message': 'Bericht',
    'profile_loading': 'Laden...',
    'profile_anonymous': 'Geen naam',

    'onb_welcome_title': 'Welkom',
    'onb_welcome_subtitle': 'Vertel ons hoe we je in gesprekken kunnen noemen.',
    'onb_language_title': 'Jouw taal',
    'onb_language_subtitle':
        'Kies de taal die je spreekt. De taal van de andere persoon wordt automatisch gedetecteerd wanneer hij deelneemt aan het gesprek.',
    'onb_first_name_label': 'Voornaam',
    'onb_first_name_hint': 'bijv. Alex',
    'onb_next': 'Volgende',
    'onb_back': 'Terug',
    'onb_finish': 'Aan de slag',
    'onb_save': 'Opslaan',
    'onb_need_name': 'Voer je voornaam in.',
    'onb_need_language': 'Kies de taal die je spreekt.',
    'onb_language_picker_label': 'De taal die je spreekt',
    'onb_profile_title': 'Jouw profiel',
    'onb_translation_help':
        'In een gesprek vertalen we de stem van de andere persoon automatisch naar jouw taal en die van jou naar die van hen.',

    'join_title': 'Een kamer binnengaan',
    'join_desc':
        'Kies een kamernaam en deel deze met een andere persoon. Jullie moeten beiden dezelfde naam gebruiken om 1-op-1 te verbinden.',
    'join_room_label': 'Kamernaam',
    'join_room_hint': 'bijv. diner-met-sam',
    'join_name_label': 'Jouw voornaam',
    'join_name_hint': 'Hoe anderen je zullen zien',
    'join_speak': 'Je spreekt {lang}',
    'join_no_lang': 'Geen taal gekozen',
    'join_lang_subtitle': 'De taal van de andere persoon wordt automatisch gedetecteerd.',
    'join_edit_profile': 'Profiel bewerken',
    'join_error_room': 'Voer een kamernaam (3+ tekens) en je voornaam in.',
    'join_error_room_format':
        'Kamernaam moet 3-64 tekens lang zijn: alleen letters, cijfers, _ en - (geen spaties of #). Voorbeeld: diner-met-sam',
    'join_error_lang': 'Kies je taal in je profiel voordat je deelneemt.',
    'join_button': 'Oproep starten',
    'join_header_title': 'Oproepen',
    'join_header_subtitle': 'LiveKit · 1-op-1',
    'join_header_token_server': 'Token-server: {api}',
    'join_header_profile_tooltip': 'Jouw profiel',
  };

  // ─── Arabic ───────────────────────────────────────────────────────────────
  static const Map<String, String> _ar = {
    'nav_search': 'بحث',
    'nav_call': 'مكالمة',
    'nav_chat': 'دردشة',
    'nav_tab3': 'الملف الشخصي',
    'tab_placeholder_soon': 'قريباً',
    'profile_title': 'الملف الشخصي',
    'profile_followers': 'المتابعون',
    'profile_following': 'يتابع',
    'block': 'حظر',
    'unblock': 'إلغاء الحظر',
    'delete': 'حذف',
    'save': 'حفظ',
    'restart': 'البدء من جديد',
    'discover_title': 'Discover',
    'search_chercher': 'بحث',
    'search_friend_hint': 'الاسم الأول للصديق',
    'filters': 'فلاتر',
    'search_intro_hint': 'اكتب الأحرف الأولى من اسم.',
    'discover_done': 'هذا كل شيء لليوم',
    'send_emoji': 'إرسال 👋',
    'add_friend_short': 'إضافة',
    'like_save_failed': 'تعذر حفظ الإعجاب.',
    'friendship_friend': 'صديق',
    'friendship_sent': 'مُرسَل',
    'friendship_pending_in': 'بانتظار القبول',
    'messages_title': 'الرسائل',
    'chat_no_friends_title': 'لا أصدقاء بعد',
    'chat_no_friends_body':
        'اذهب إلى علامة التبويب البحث للعثور على شخص بالاسم، ثم أرسل طلب صداقة للدردشة معه.',
    'chat_no_name': 'بدون اسم',
    'chat_tap_to_chat': 'اضغط للدردشة',
    'tooltip_more': 'المزيد',
    'view_profile': 'عرض الملف الشخصي',
    'block_peer_q': 'حظر {name}؟',
    'unblock_peer_q': 'إلغاء حظر {name}؟',
    'block_peer_body':
        'لن يتمكن هذا الشخص من العثور عليك أو الاتصال بك أو إجراء مكالمة. يمكنك التراجع من الإعدادات ← المحظورين.',
    'unblock_peer_body':
        'سيتمكن هذا الشخص من العثور عليك ومراسلتك ورؤية رسائلك مرة أخرى.',
    'no_messages': 'لا توجد رسائل — اكتب الأولى!',
    'tooltip_call': 'اتصل',
    'composer_message_hint': 'رسالة',
    'profile_default_title': 'الملف الشخصي',
    'delete_photo_q': 'حذف الصورة؟',
    'delete_photo_body':
        'سيتم إزالة صورة Discover الخاصة بك. يمكنك تحميل صورة جديدة في أي وقت.',
    'bio_editor_title': 'نبذة عنك',
    'incoming_someone': 'شخص ما',
    'cant_join_call': 'تعذر الانضمام للمكالمة: {msg}',
    'incoming_call_label': 'مكالمة واردة…',
    'decline': 'رفض',
    'accept': 'قبول',
    'who_liked_me': 'من أعجب بي',
    'no_one_liked_yet': 'لم يعجب بك أحد بعد',
    'like_explainer':
        'عندما يضغط شخص ما على ❤ في بطاقة Discover الخاصة بك، ستراه هنا.',
    'profile_speaks': 'يتحدث {lang}',
    'profile_no_language': 'لا توجد لغة',
    'profile_edit': 'تعديل',
    'profile_message': 'رسالة',
    'profile_loading': 'جارٍ التحميل...',
    'profile_anonymous': 'بدون اسم',

    'onb_welcome_title': 'مرحباً',
    'onb_welcome_subtitle': 'أخبرنا كيف نناديك في المكالمات.',
    'onb_language_title': 'لغتك',
    'onb_language_subtitle':
        'اختر اللغة التي تتحدثها. يتم اكتشاف لغة الشخص الآخر تلقائياً عند انضمامه إلى المكالمة.',
    'onb_first_name_label': 'الاسم الأول',
    'onb_first_name_hint': 'مثل أليكس',
    'onb_next': 'التالي',
    'onb_back': 'رجوع',
    'onb_finish': 'ابدأ',
    'onb_save': 'حفظ',
    'onb_need_name': 'أدخل اسمك الأول.',
    'onb_need_language': 'اختر اللغة التي تتحدثها.',
    'onb_language_picker_label': 'اللغة التي تتحدثها',
    'onb_profile_title': 'ملفك الشخصي',
    'onb_translation_help':
        'في المكالمة، سنترجم تلقائياً صوت الشخص الآخر إلى لغتك وصوتك إلى لغته.',

    'join_title': 'الانضمام إلى غرفة',
    'join_desc':
        'اختر اسم غرفة وشاركه مع شخص آخر. يجب أن يستخدم كلاكما الاسم نفسه للاتصال 1-إلى-1.',
    'join_room_label': 'اسم الغرفة',
    'join_room_hint': 'مثل dinner-with-sam',
    'join_name_label': 'اسمك الأول',
    'join_name_hint': 'كما سيراك الآخرون',
    'join_speak': 'تتحدث {lang}',
    'join_no_lang': 'لم يتم اختيار لغة',
    'join_lang_subtitle': 'يتم اكتشاف لغة الشخص الآخر تلقائياً.',
    'join_edit_profile': 'تعديل ملفك الشخصي',
    'join_error_room': 'أدخل اسم غرفة (3+ أحرف) واسمك الأول.',
    'join_error_room_format':
        'يجب أن يكون اسم الغرفة 3-64 حرفاً: حروف وأرقام و _ و - فقط (بدون مسافات أو #). مثال: dinner-with-sam',
    'join_error_lang': 'اختر لغتك في ملفك الشخصي قبل الانضمام.',
    'join_button': 'بدء المكالمة',
    'join_header_title': 'المكالمات',
    'join_header_subtitle': 'LiveKit · 1-إلى-1',
    'join_header_token_server': 'خادم التوكن: {api}',
    'join_header_profile_tooltip': 'ملفك الشخصي',
  };

  // ─── Russian ──────────────────────────────────────────────────────────────
  static const Map<String, String> _ru = {
    'nav_search': 'Поиск',
    'nav_call': 'Звонок',
    'nav_chat': 'Чат',
    'nav_tab3': 'Профиль',
    'tab_placeholder_soon': 'Скоро',
    'profile_title': 'Профиль',
    'profile_followers': 'Подписчики',
    'profile_following': 'Подписки',
    'block': 'Заблокировать',
    'unblock': 'Разблокировать',
    'delete': 'Удалить',
    'save': 'Сохранить',
    'restart': 'Начать заново',
    'discover_title': 'Discover',
    'search_chercher': 'Поиск',
    'search_friend_hint': 'Имя друга',
    'filters': 'Фильтры',
    'search_intro_hint': 'Введите первые буквы имени.',
    'discover_done': 'На сегодня всё',
    'send_emoji': 'Отправить 👋',
    'add_friend_short': 'Добавить',
    'like_save_failed': 'Не удалось сохранить лайк.',
    'friendship_friend': 'Друг',
    'friendship_sent': 'Отправлено',
    'friendship_pending_in': 'Принять',
    'messages_title': 'Сообщения',
    'chat_no_friends_title': 'Пока нет друзей',
    'chat_no_friends_body':
        'Перейди во вкладку Поиск, чтобы найти кого-то по имени, затем отправь запрос в друзья, чтобы общаться.',
    'chat_no_name': 'Без имени',
    'chat_tap_to_chat': 'Нажми, чтобы поговорить',
    'tooltip_more': 'Ещё',
    'view_profile': 'Посмотреть профиль',
    'block_peer_q': 'Заблокировать {name}?',
    'unblock_peer_q': 'Разблокировать {name}?',
    'block_peer_body':
        'Этот человек больше не сможет тебя найти, связаться с тобой или позвонить. Можно отменить в Настройки → Заблокированные.',
    'unblock_peer_body':
        'Этот человек снова сможет тебя найти, связаться с тобой и видеть твои сообщения.',
    'no_messages': 'Нет сообщений — напиши первое!',
    'tooltip_call': 'Позвонить',
    'composer_message_hint': 'Сообщение',
    'profile_default_title': 'Профиль',
    'delete_photo_q': 'Удалить фото?',
    'delete_photo_body':
        'Твоё фото Discover будет удалено. Ты можешь загрузить новое в любой момент.',
    'bio_editor_title': 'О себе',
    'incoming_someone': 'Кто-то',
    'cant_join_call': 'Не удалось присоединиться к звонку: {msg}',
    'incoming_call_label': 'Входящий звонок…',
    'decline': 'Отклонить',
    'accept': 'Принять',
    'who_liked_me': 'Кто мне поставил лайк',
    'no_one_liked_yet': 'Тебя ещё никто не лайкнул',
    'like_explainer':
        'Когда кто-то нажмёт ❤ на твоей карточке Discover, ты увидишь его здесь.',
    'profile_speaks': 'Говорит на {lang}',
    'profile_no_language': 'Нет языка',
    'profile_edit': 'Изменить',
    'profile_message': 'Сообщение',
    'profile_loading': 'Загрузка...',
    'profile_anonymous': 'Без имени',

    'onb_welcome_title': 'Добро пожаловать',
    'onb_welcome_subtitle': 'Скажи, как тебя называть в звонках.',
    'onb_language_title': 'Твой язык',
    'onb_language_subtitle':
        'Выбери язык, на котором ты говоришь. Язык собеседника определяется автоматически, когда он присоединяется к звонку.',
    'onb_first_name_label': 'Имя',
    'onb_first_name_hint': 'напр. Alex',
    'onb_next': 'Далее',
    'onb_back': 'Назад',
    'onb_finish': 'Начать',
    'onb_save': 'Сохранить',
    'onb_need_name': 'Введи своё имя.',
    'onb_need_language': 'Выбери язык, на котором ты говоришь.',
    'onb_language_picker_label': 'Язык, на котором ты говоришь',
    'onb_profile_title': 'Твой профиль',
    'onb_translation_help':
        'Во время звонка мы автоматически переведём голос собеседника на твой язык, а твой — на его.',

    'join_title': 'Войти в комнату',
    'join_desc':
        'Выбери название комнаты и поделись им с другим человеком. Вы оба должны использовать одно и то же название для связи 1-на-1.',
    'join_room_label': 'Название комнаты',
    'join_room_hint': 'напр. dinner-with-sam',
    'join_name_label': 'Твоё имя',
    'join_name_hint': 'Как тебя увидят другие',
    'join_speak': 'Ты говоришь на {lang}',
    'join_no_lang': 'Язык не выбран',
    'join_lang_subtitle': 'Язык собеседника определяется автоматически.',
    'join_edit_profile': 'Изменить профиль',
    'join_error_room': 'Введи название комнаты (3+ символа) и своё имя.',
    'join_error_room_format':
        'Название комнаты должно быть 3-64 символа: только буквы, цифры, _ и - (без пробелов и #). Пример: dinner-with-sam',
    'join_error_lang': 'Выбери язык в профиле перед подключением.',
    'join_button': 'Начать звонок',
    'join_header_title': 'Звонки',
    'join_header_subtitle': 'LiveKit · 1-на-1',
    'join_header_token_server': 'Сервер токенов: {api}',
    'join_header_profile_tooltip': 'Твой профиль',
  };

  // ─── Chinese (Simplified) ─────────────────────────────────────────────────
  static const Map<String, String> _zh = {
    'nav_search': '搜索',
    'nav_call': '通话',
    'nav_chat': '聊天',
    'nav_tab3': '个人资料',
    'tab_placeholder_soon': '即将推出',
    'profile_title': '个人资料',
    'profile_followers': '粉丝',
    'profile_following': '关注',
    'block': '屏蔽',
    'unblock': '解除屏蔽',
    'delete': '删除',
    'save': '保存',
    'restart': '重新开始',
    'discover_title': 'Discover',
    'search_chercher': '搜索',
    'search_friend_hint': '朋友的名字',
    'filters': '筛选',
    'search_intro_hint': '输入名字的前几个字母。',
    'discover_done': '今天就这样吧',
    'send_emoji': '发送 👋',
    'add_friend_short': '添加',
    'like_save_failed': '无法保存喜欢。',
    'friendship_friend': '好友',
    'friendship_sent': '已发送',
    'friendship_pending_in': '待接受',
    'messages_title': '消息',
    'chat_no_friends_title': '还没有朋友',
    'chat_no_friends_body':
        '前往搜索标签页，按名字找到某人，然后发送好友请求来聊天。',
    'chat_no_name': '无名字',
    'chat_tap_to_chat': '点击聊天',
    'tooltip_more': '更多',
    'view_profile': '查看个人资料',
    'block_peer_q': '屏蔽 {name}？',
    'unblock_peer_q': '解除屏蔽 {name}？',
    'block_peer_body':
        '此人将无法再找到你、联系你或拨打你的电话。你可以从设置 → 已屏蔽中撤销。',
    'unblock_peer_body':
        '此人将能够再次找到你、联系你并查看你的消息。',
    'no_messages': '没有消息——写下第一条！',
    'tooltip_call': '通话',
    'composer_message_hint': '消息',
    'profile_default_title': '个人资料',
    'delete_photo_q': '删除照片？',
    'delete_photo_body':
        '你的 Discover 照片将被删除。你可以随时上传新的。',
    'bio_editor_title': '你的简介',
    'incoming_someone': '某人',
    'cant_join_call': '无法加入通话：{msg}',
    'incoming_call_label': '来电…',
    'decline': '拒绝',
    'accept': '接受',
    'who_liked_me': '谁喜欢我',
    'no_one_liked_yet': '还没有人喜欢你',
    'like_explainer':
        '当有人点击你 Discover 卡片上的 ❤ 时，你会在这里看到。',
    'profile_speaks': '说{lang}',
    'profile_no_language': '没有语言',
    'profile_edit': '编辑',
    'profile_message': '消息',
    'profile_loading': '加载中...',
    'profile_anonymous': '无名',

    'onb_welcome_title': '欢迎',
    'onb_welcome_subtitle': '告诉我们在通话中如何称呼你。',
    'onb_language_title': '你的语言',
    'onb_language_subtitle':
        '选择你使用的语言。对方加入通话时，他们的语言会自动检测。',
    'onb_first_name_label': '名字',
    'onb_first_name_hint': '例如 Alex',
    'onb_next': '下一步',
    'onb_back': '返回',
    'onb_finish': '开始',
    'onb_save': '保存',
    'onb_need_name': '请输入你的名字。',
    'onb_need_language': '请选择你使用的语言。',
    'onb_language_picker_label': '你使用的语言',
    'onb_profile_title': '你的个人资料',
    'onb_translation_help':
        '在通话中，我们将自动把对方的声音翻译成你的语言，把你的声音翻译成对方的语言。',

    'join_title': '加入房间',
    'join_desc':
        '选择一个房间名称并与他人分享。你们必须使用相同的名称才能进行 1 对 1 连接。',
    'join_room_label': '房间名称',
    'join_room_hint': '例如 dinner-with-sam',
    'join_name_label': '你的名字',
    'join_name_hint': '其他人看到你的方式',
    'join_speak': '你说{lang}',
    'join_no_lang': '未选择语言',
    'join_lang_subtitle': '对方的语言会自动检测。',
    'join_edit_profile': '编辑你的个人资料',
    'join_error_room': '请输入房间名称（3+ 个字符）和你的名字。',
    'join_error_room_format':
        '房间名称必须为 3-64 个字符：仅限字母、数字、_ 和 -（不能有空格或 #）。例如：dinner-with-sam',
    'join_error_lang': '加入前请在个人资料中选择你的语言。',
    'join_button': '开始通话',
    'join_header_title': '通话',
    'join_header_subtitle': 'LiveKit · 1 对 1',
    'join_header_token_server': 'Token 服务器：{api}',
    'join_header_profile_tooltip': '你的个人资料',
  };

  // ─── Japanese ─────────────────────────────────────────────────────────────
  static const Map<String, String> _ja = {
    'nav_search': '検索',
    'nav_call': '通話',
    'nav_chat': 'チャット',
    'nav_tab3': 'プロフィール',
    'tab_placeholder_soon': '近日公開',
    'profile_title': 'プロフィール',
    'profile_followers': 'フォロワー',
    'profile_following': 'フォロー中',
    'block': 'ブロック',
    'unblock': 'ブロック解除',
    'delete': '削除',
    'save': '保存',
    'restart': 'やり直す',
    'discover_title': 'Discover',
    'search_chercher': '検索',
    'search_friend_hint': '友達の名前',
    'filters': 'フィルター',
    'search_intro_hint': '名前の最初の文字を入力してください。',
    'discover_done': '今日はここまで',
    'send_emoji': '送信 👋',
    'add_friend_short': '追加',
    'like_save_failed': 'いいねを保存できませんでした。',
    'friendship_friend': '友達',
    'friendship_sent': '送信済み',
    'friendship_pending_in': '承認待ち',
    'messages_title': 'メッセージ',
    'chat_no_friends_title': 'まだ友達がいません',
    'chat_no_friends_body':
        '検索タブで名前から相手を見つけ、友達リクエストを送ってチャットを始めましょう。',
    'chat_no_name': '名前なし',
    'chat_tap_to_chat': 'タップしてチャット',
    'tooltip_more': 'もっと見る',
    'view_profile': 'プロフィールを見る',
    'block_peer_q': '{name} をブロックしますか？',
    'unblock_peer_q': '{name} のブロックを解除しますか？',
    'block_peer_body':
        'この人はあなたを見つけたり、連絡したり、通話することができなくなります。設定 → ブロック済み から取り消せます。',
    'unblock_peer_body':
        'この人は再びあなたを見つけたり、連絡したり、メッセージを見ることができます。',
    'no_messages': 'メッセージなし — 最初の一通を書きましょう！',
    'tooltip_call': '通話',
    'composer_message_hint': 'メッセージ',
    'profile_default_title': 'プロフィール',
    'delete_photo_q': '写真を削除しますか？',
    'delete_photo_body':
        'Discover 写真が削除されます。いつでも新しい写真をアップロードできます。',
    'bio_editor_title': '自己紹介',
    'incoming_someone': '誰か',
    'cant_join_call': '通話に参加できません: {msg}',
    'incoming_call_label': '着信中…',
    'decline': '拒否',
    'accept': '応答',
    'who_liked_me': 'いいねをくれた人',
    'no_one_liked_yet': 'まだ誰もあなたにいいねしていません',
    'like_explainer':
        '誰かがあなたの Discover カードの ❤ をタップすると、ここに表示されます。',
    'profile_speaks': '{lang}を話します',
    'profile_no_language': '言語なし',
    'profile_edit': '編集',
    'profile_message': 'メッセージ',
    'profile_loading': '読み込み中...',
    'profile_anonymous': '名前なし',

    'onb_welcome_title': 'ようこそ',
    'onb_welcome_subtitle': '通話で呼ばれる名前を教えてください。',
    'onb_language_title': 'あなたの言語',
    'onb_language_subtitle':
        '話す言語を選んでください。相手の言語は通話に参加したときに自動的に検出されます。',
    'onb_first_name_label': '名前',
    'onb_first_name_hint': '例: Alex',
    'onb_next': '次へ',
    'onb_back': '戻る',
    'onb_finish': '始める',
    'onb_save': '保存',
    'onb_need_name': '名前を入力してください。',
    'onb_need_language': '話す言語を選んでください。',
    'onb_language_picker_label': '話す言語',
    'onb_profile_title': 'プロフィール',
    'onb_translation_help':
        '通話中、相手の声をあなたの言語に、あなたの声を相手の言語に自動翻訳します。',

    'join_title': 'ルームに参加',
    'join_desc':
        'ルーム名を選んで、他の人と共有してください。1対1で接続するには、同じ名前を使う必要があります。',
    'join_room_label': 'ルーム名',
    'join_room_hint': '例: dinner-with-sam',
    'join_name_label': 'あなたの名前',
    'join_name_hint': '他の人に表示される名前',
    'join_speak': 'あなたは{lang}を話します',
    'join_no_lang': '言語が選択されていません',
    'join_lang_subtitle': '相手の言語は自動的に検出されます。',
    'join_edit_profile': 'プロフィールを編集',
    'join_error_room': 'ルーム名（3文字以上）とあなたの名前を入力してください。',
    'join_error_room_format':
        'ルーム名は3〜64文字: 英数字、_、- のみ（スペースや # は不可）。例: dinner-with-sam',
    'join_error_lang': '参加する前にプロフィールで言語を選んでください。',
    'join_button': '通話を開始',
    'join_header_title': '通話',
    'join_header_subtitle': 'LiveKit · 1対1',
    'join_header_token_server': 'トークンサーバー: {api}',
    'join_header_profile_tooltip': 'プロフィール',
  };

  // ─── Korean ───────────────────────────────────────────────────────────────
  static const Map<String, String> _ko = {
    'nav_search': '검색',
    'nav_call': '통화',
    'nav_chat': '채팅',
    'nav_tab3': '프로필',
    'tab_placeholder_soon': '곧 출시',
    'profile_title': '프로필',
    'profile_followers': '팔로워',
    'profile_following': '팔로잉',
    'block': '차단',
    'unblock': '차단 해제',
    'delete': '삭제',
    'save': '저장',
    'restart': '다시 시작',
    'discover_title': 'Discover',
    'search_chercher': '검색',
    'search_friend_hint': '친구 이름',
    'filters': '필터',
    'search_intro_hint': '이름의 처음 몇 글자를 입력하세요.',
    'discover_done': '오늘은 여기까지',
    'send_emoji': '보내기 👋',
    'add_friend_short': '추가',
    'like_save_failed': '좋아요를 저장할 수 없습니다.',
    'friendship_friend': '친구',
    'friendship_sent': '보냄',
    'friendship_pending_in': '수락 대기',
    'messages_title': '메시지',
    'chat_no_friends_title': '아직 친구가 없습니다',
    'chat_no_friends_body':
        '검색 탭에서 이름으로 누군가를 찾고, 친구 요청을 보내서 대화를 시작하세요.',
    'chat_no_name': '이름 없음',
    'chat_tap_to_chat': '대화하려면 탭하세요',
    'tooltip_more': '더 보기',
    'view_profile': '프로필 보기',
    'block_peer_q': '{name} 차단하시겠습니까?',
    'unblock_peer_q': '{name} 차단을 해제하시겠습니까?',
    'block_peer_body':
        '이 사람은 더 이상 당신을 찾거나, 연락하거나, 전화할 수 없습니다. 설정 → 차단됨에서 취소할 수 있습니다.',
    'unblock_peer_body':
        '이 사람이 다시 당신을 찾고, 연락하고, 메시지를 볼 수 있게 됩니다.',
    'no_messages': '메시지 없음 — 첫 메시지를 작성하세요!',
    'tooltip_call': '전화',
    'composer_message_hint': '메시지',
    'profile_default_title': '프로필',
    'delete_photo_q': '사진을 삭제하시겠습니까?',
    'delete_photo_body':
        'Discover 사진이 제거됩니다. 언제든지 새 사진을 업로드할 수 있습니다.',
    'bio_editor_title': '자기소개',
    'incoming_someone': '누군가',
    'cant_join_call': '통화에 참여할 수 없습니다: {msg}',
    'incoming_call_label': '수신 전화…',
    'decline': '거절',
    'accept': '수락',
    'who_liked_me': '나를 좋아한 사람',
    'no_one_liked_yet': '아직 아무도 좋아요를 누르지 않았습니다',
    'like_explainer':
        '누군가 당신의 Discover 카드의 ❤를 탭하면 여기에 표시됩니다.',
    'profile_speaks': '{lang}를 사용합니다',
    'profile_no_language': '언어 없음',
    'profile_edit': '편집',
    'profile_message': '메시지',
    'profile_loading': '불러오는 중...',
    'profile_anonymous': '이름 없음',

    'onb_welcome_title': '환영합니다',
    'onb_welcome_subtitle': '통화에서 어떻게 부를지 알려주세요.',
    'onb_language_title': '당신의 언어',
    'onb_language_subtitle':
        '사용하는 언어를 선택하세요. 상대방의 언어는 통화에 참여할 때 자동으로 감지됩니다.',
    'onb_first_name_label': '이름',
    'onb_first_name_hint': '예: Alex',
    'onb_next': '다음',
    'onb_back': '뒤로',
    'onb_finish': '시작하기',
    'onb_save': '저장',
    'onb_need_name': '이름을 입력하세요.',
    'onb_need_language': '사용하는 언어를 선택하세요.',
    'onb_language_picker_label': '사용하는 언어',
    'onb_profile_title': '프로필',
    'onb_translation_help':
        '통화 중에 상대방의 음성을 당신의 언어로, 당신의 음성을 상대방의 언어로 자동 번역합니다.',

    'join_title': '방 참여하기',
    'join_desc':
        '방 이름을 선택하고 다른 사람과 공유하세요. 1대1로 연결하려면 같은 이름을 사용해야 합니다.',
    'join_room_label': '방 이름',
    'join_room_hint': '예: dinner-with-sam',
    'join_name_label': '당신의 이름',
    'join_name_hint': '다른 사람에게 보여질 이름',
    'join_speak': '{lang}를 사용합니다',
    'join_no_lang': '선택된 언어가 없습니다',
    'join_lang_subtitle': '상대방의 언어는 자동으로 감지됩니다.',
    'join_edit_profile': '프로필 편집',
    'join_error_room': '방 이름(3자 이상)과 이름을 입력하세요.',
    'join_error_room_format':
        '방 이름은 3-64자여야 합니다: 영문자, 숫자, _, -만 사용 (공백이나 # 불가). 예: dinner-with-sam',
    'join_error_lang': '참여하기 전에 프로필에서 언어를 선택하세요.',
    'join_button': '통화 시작',
    'join_header_title': '통화',
    'join_header_subtitle': 'LiveKit · 1대1',
    'join_header_token_server': '토큰 서버: {api}',
    'join_header_profile_tooltip': '프로필',
  };
}
